build_script:
  - msbuild RemoteViewing.sln /p:Configuration=Release /p:Platform="Any CPU" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

on_success:
  - cmd: nuget pack RemoteViewing.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - ps: Push-AppveyorArtifact "RemoteViewing.$($env:APPVEYOR_BUILD_VERSION).nupkg"